% Script to generate maps of critical hmin and number of initial minima.
% A few examples are given below, for circles and ellipses. 
% Both circles and ellipses and combinations of these can be generated and
% hmin maps determined. The main variables are :
% The semi-major axes of both ellipses, a1 and a2; semi-minor axes b1 and
% b2; Domain size N pixels and the angle of inclination of the second
% ellipse with respect to the horizontal, theta. 
% Circles can be generated simply by putting a1 = b1 = radius.

% Hardware requirements: Each of the below sections takes a few hours of
% runtime, details are given in the readme file. Hence, we recommend to run
% only one of them for a single angle on a cluster. If a cluster is not
% available, a dedicated workstation must be used, but the runtime could be
% much higher for each case. A way to check correctness and use lesser time
% is to increase the xStep parameter in getHmap_par.m. Larger values of
% xStep simply omits several points and samples the 2D cartesian grid at a
% few points only, reducing runtime. 

%% Smaller ellipses
% Figure 17 top row Two ellipses with aspect ratio 1:2 each, smaller, second ellipse at zero degrees 
% Other angles can be generated by varying theta.

%%%% UNCOMMENT LINES 25 TO 43 TO RUN A PAIR OF SMALLER ELLIPSES %%%%
%%%% Ellipse dimensions
% a1 = 100
% b1 = 50
% a2 = 100
% b2 = 50
% 
%%%% Domain size
% N = 1000
% 
%%%% Inclination angle
% theta = 0
% 
% A = zeros(4,1);
% 
% A(1) = b1
% A(2) = a1
% A(3) = b2
% A(4) = a2
% 
% [hMap nMap] = getHmap_par(N,A,theta);

%%%% SMALLER ELLIPSE BLOCK ENDS %%%%

%% Larger ellipses
% Figure 17 bottom row Two ellipses with aspect ratio 1:2 each, bigger, second ellipse at zero degrees 
% Other angles can be generated by varying theta.
% 
%%%% UNCOMMENT LINES 53 TO 71 TO RUN A PAIR OF LARGER ELLIPSES %%%%
%%% Ellipse dimensions
% a1 = 200
% b1 = 100
% a2 = 200
% b2 = 100
% 
%%% Domain size, larger for bigger ellipses
% N = 1200
% 
%%% Inclination angle
% theta = 0
% 
% A = zeros(4,1);
% 
% A(1) = b1
% A(2) = a1
% A(3) = b2
% A(4) = a2
% 
% [hMap nMap] = getHmap_par(N,A,theta);
%
%%%% LARGER ELLIPSE BLOCK ENDS %%%%

%% Circles
% % Figure 16c, circles of radii 50 and 100 pixels
% Note that any other pair of circles can be easily checked by changing the
% below dimension a1,b1,a2,b2

%%%% UNCOMMENT LINES 82 TO 100 TO RUN A PAIR OF CIRCLES %%%%
%%% Circle dimensions
% a1 = 100
% b1 = 100
% a2 = 50
% b2 = 50
% 
%%% Domain size
% N = 1000
% 
%%% Inclination angle
% theta = 0
% 
% A = zeros(4,1);
% 
% A(1) = b1
% A(2) = a1
% A(3) = b2
% A(4) = a2
% 
% [hMap nMap] = getHmap_par(N,A,theta);
%
%%%% CIRCLE BLOCK ENDS %%%%